### PR TITLE
Enable udp in str2str and rtkrcv

### PR DESCRIPTION
**Pull request by yhzyhzyhz**
- enable udp in str2str and rtkrcv
- sync output stream1 with stream0 output format

### CODE REVIEW

**Comment by ourairquality** [comment]
This might have all been addressed now.

**Comment by rtklibexplorer** [comment]
Given the age of this request, the age of the demo5_b33 branch, and the reasonableness of the request, it doesn't look like it should cause any harm so I am accepting the changes.

**Comment by ourairquality** [comment]
The fix for the second set of solution options was inadequate. This was noted independently and addressed in the pending https://github.com/rtklibexplorer/RTKLIB/pull/285

There were more issues with UDP support, and the UDP server stream is an input stream so should not be added to output stream options, addressed in https://github.com/rtklibexplorer/RTKLIB/pull/370

**Comment by rtklibexplorer** [comment]
Agreed, will follow up with the more complete solution in the main branch

**Pull request closed without merging**
