### PR TITLE
Fix memory leak in holdamb()

### PR DESCRIPTION
**Pull request by anton-chy**

### CODE REVIEW

**Comment by rtklibexplorer** [comment]
Fix memory leak in holdamb()

**Comment by rtklibexplorer** [comment]
Thanks Anton!

**Comment by egorf** [comment]
@anton-chy Thank you for this. Just ended a heavy valgrind session to find the root of the problem. Turns out our fork also had a similar issue, so both of them are fixed now.

**Comment by anton-chy** [comment]
That's great! I too used valgrind (massif) to find it.

**Pull request merged**
