### PR TITLE
Remove links to librt

### PR DESCRIPTION
**Pull request by daz**
This enables compilation on macOS

### CODE REVIEW

**Comment by ourairquality** [comment]
Here on Fedora 39 librt and even libpthread appear empty. Perhaps these have all been integrated into libc now. So perhaps there is no need to like with librt just for linux. All the console apps build fine without linking with librt or even libpthread.

**Comment by ourairquality** [comment]
RPi Debian GNU/Linux 12 also does not require linking with librt which appears to be empty. The following might explain this direction, and it might be new with glibc-2.34
https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread

**Comment by daz** [comment]
I removed links to both and it builds on macOS and Ubuntu 2024.04

**Comment by ourairquality** [comment]
Perhaps keep linking to libpthread if it is not causing issues, as it may still be needed for some environments.

**Comment by dwrobel** [comment]
>Perhaps keep linking to libpthread

For linking `pthread` please consider using `-pthread` option 

From gcc(1):
```
-pthread
           Define additional macros required for using the POSIX threads library.  You should use this option consistently for both compilation and linking.  This option is supported on GNU/Linux targets, most other Unix
           derivatives, and also on x86 Cygwin and MinGW targets.
```

**Pull request merged**
