### PR TITLE
Fix qtapp and consapp compilation to recent options, QT and Mac compile

### PR DESCRIPTION
**Pull request by drf5n**
This solves these issues for my non-windows Mac & Homebrew setup.

https://github.com/rtklibexplorer/RTKLIB/issues/135

https://github.com/rtklibexplorer/RTKLIB/issues/127

It also has a workaround for the interaction between RTK's lock() function and Mac's mutex lock() templates. 

It also makes use of the pull in 

https://github.com/rtklibexplorer/RTKLIB/pull/107

### CODE REVIEW

**Comment by pkkrusty** [comment]
Lots of open PRs on this fork and original rtklib. Recent and many months old. Are the original admins no longer actively involved in the projects? If not, anyone have recommendations for a fork that is more actively maintained?

**Comment by gaofenzi** [comment]
您好，辛苦啦！梦寒已经收到您的珍贵来件，会在最短的时间内给予您最想要的答复！

**Comment by rtklibexplorer** [comment]
It's true that I haven't been good about keeping up with the PR requests, especially the most recent ones.  I will try and review these in the near future.  Regarding the Qt builds, support for them was dropped in the original (2.4.3) RTKLIB and I have not been supporting them either although the original code is still present in the repo in case anyone else wants to resurrect it.  I do actively maintain the Windows GUI and CUI apps and the linux CUI apps.

**Comment by rtklibexplorer** [comment]
Merged most of these changes into the code with the 5/17/2023 commit.  Removing the libraries from the gcc makefiles breaks my linux builds so I did not include these.

**Pull request closed without merging**
