### PR TITLE
Bug in ppp.c when using rtcm: Galileo was not considered

### PR DESCRIPTION
**Pull request by alecianfe**
Variable ix was used without being initialized. The application crashed when sys was equal to SYS_GAL

### CODE REVIEW

**Comment by alecianfe** [comment]
Probably it's better to use the following CODE_L1X and CODE_L7X since the ublox F9 supports Galileo E1-B/C (1575.42 MHz) and E5b (1207.140 MHz)

**Comment by alecianfe** [comment]
I've added some more free to avoid memory leak

**Comment by GHolk** [comment]
hey alecianfe. does this patch still meaningful now?
I does not apply this patch, but use the demo5 code from rtklib explorer, and I still can perform ppp with galileo satellites.

**Comment by rtklibexplorer** [comment]
Added in 11/21/20 commits

**Pull request closed without merging**
